clear all
set more off
capture log close
log using "diagnostics.log", replace text

*=====================================================*
* 1. Load and Clean Dataset
*=====================================================*
use "houseprices_clean.dta", clear
tsset qdate

* Keep only complete observations
keep if !missing(ln_hpi, ln_bank_rate, ln_income, ln_completions)

* Create differenced variables
gen D_ln_hpi = D.ln_hpi
gen D_ln_bank_rate = D.ln_bank_rate
gen D_ln_income = D.ln_income
gen D_ln_completions = D.ln_completions

* Drop first obs (generated by differencing)
drop if missing(D_ln_hpi, D_ln_bank_rate, D_ln_income, D_ln_completions)

*=====================================================*
* 2. Re-estimate ARDL(1,2,3,4) Model with Robust SEs
*=====================================================*
reg D_ln_hpi L.ln_hpi ///
    D_ln_bank_rate L.D_ln_bank_rate ///
    D_ln_income L.D_ln_income L2.D_ln_income ///
    D_ln_completions L.D_ln_completions L2.D_ln_completions L3.D_ln_completions, ///
    vce(robust)

* Save residuals
predict resid_ardl, residuals

*=====================================================*
* 3. Serial Correlation Tests (re-run without robust SEs)
*=====================================================*
reg D_ln_hpi L.ln_hpi ///
    D_ln_bank_rate L.D_ln_bank_rate ///
    D_ln_income L.D_ln_income L2.D_ln_income ///
    D_ln_completions L.D_ln_completions L2.D_ln_completions L3.D_ln_completions

estat bgodfrey, lags(1)
estat bgodfrey, lags(4)
dwstat

*=====================================================*
* 4. Heteroskedasticity Test
*=====================================================*
* Already using robust SEs, but confirm diagnostic
estat hettest resid_ardl, iid

*=====================================================*
* 5. Normality Tests
*=====================================================*
sktest resid_ardl
swilk resid_ardl

log close
